<div class="w-full">
    <h3 class="font-bold">Estantería del usuario</h3>
    <?php if (empty($_GET["id"])): ?>
        <div class="w-full my-2">
            <a href="/home/agregar" class="inline-block border px-4 py-1 bg-red-600 text-white hover:bg-red-700 rounded">Agregar</a>
        </div>
    <?php endif; ?>
    <?php if (isset($libros)): ?>
        <div class="grid grid-cols-6 gap-2">
            <?php foreach ($libros as $libro): ?>
                <a href="/home/libro&id=<?=$libro->getId()?>" class="border box-border p-2 flex flex-col rounded hover:bg-gray-100 text-center">
                    <p class="inline-block"><?=$libro->getTitulo()?></p>
                    <p class="inline-block"><?=$libro->getAutor()?>, <?=$libro->getYear() ? $libro->getYear() : "s.f." ?></p>
                </a>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p class="">No hay libros en la estantería</p>
    <?php endif; ?>
</div>