<div>
    <?php if (empty($_GET["id"])): ?>
        <div>
            <a href="/home/agregar">Agregar</a>
        </div>
    <?php endif; ?>
    <?php if (isset($libros)): ?>
        <?php foreach ($libros as $libro): ?>
            <a href="/home/libro&id=<?=$libro->getId()?>">
                <div class="libro">
                    <p><?=$libro->getTitulo()?></p>
                    <p><?=$libro->getAutor()?>, <?=$libro->getYear()?></p>
                </div>
            </a>
        <?php endforeach; ?>
    <?php endif; ?>
</div>