<div>
    <div>
        <!-- <button type="button" class="" data-toggle="modal" data-target="#exampleModal">
            Agregar    
        </button>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
                </div>
            </div>
        </div> -->
        <a href="/home/agregar">Agregar</a>
    </div>
    <?php if (isset($libros)): ?>
        <?php foreach ($libros as $libro): ?>
            <a href="/home/libro&id=<?=$libro->getId()?>">
                <div class="libro">
                    <p><?=$libro->getTitulo()?></p>
                    <p><?=$libro->getAutor()?>, <?=$libro->getYear()?></p>
                </div>
            </a>
        <?php endforeach; ?>
    <?php endif; ?>
</div>