<div class="w-full">
    <h3 class="text-lg text-center font-bold">Usuarios</h3>

    <?php if(isset($users)): ?>
        <div class="grid grid-cols-6 gap-2">
        <?php foreach($users as $user): ?>
            <!-- insecure view -->
            <?php if (true): ?>
            <a href="/admin/user&id=<?=$user->getId();?>" class="border box-border p-2 flex flex-col rounded hover:bg-gray-100 text-center">
                <p><?=$user->getEmail()?></p>
                <h4><?=$user->getNombre()?></h4>
            </a>
            <?php endif; ?>
        <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>