<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BiblioDevs</title>
    <link rel="stylesheet" href=<?="{$HOST}/assets/css/normalize.css"?>>
    <link rel="stylesheet" href=<?="{$HOST}/assets/css/styles.css"?>>
    <script src=<?="{$HOST}/assets/javascript/tailwind.js"?>></script>
    <script src="<?=$HOST?>assets/javascript/scripts.js"></script>
</head>
<body class="m-2">
    <header class="flex flex-row w-full justify-between items-end">
        <figure class="w-48">
            <img src=<?="{$HOST}assets/images/logo.png"?> alt="logo">
        </figure>
        <nav>
            <?php if (Utils::isAdmin()): ?>
                <a href="/admin" title="Administrar"><img class="mx-2 w-7 inline" src="<?=$HOST?>/assets/icons/administrador.png" alt="Administrador"></a>
            <?php endif; ?>

            <?php if (Utils::isLogged()): ?>
                <a href="/" title="Estantería"><img class="mx-2 w-7 inline" src="<?=$HOST?>/assets/icons/libros.png" alt="Estantería"></a>
                <a href="/user" title="Cuenta"><img class="mx-2 w-6 inline" src="<?=$HOST?>/assets/icons/usuario.png" alt="Cuenta"></a>
                <a href="/user/logout" title="Cerrar sesión"><img class="mx-2 w-6 inline" src="<?=$HOST?>/assets/icons/logout.png" alt="Cerrar sesión"></a>
            <?php else: ?>
                <a href="/user/login" class="self-end border rounded bg-red-600 text-white hover:bg-red-700 cursor-pointer outline-none py-1 px-2 my-2">Iniciar Sesion</a>
                <a href="/user/signup" class="self-end border rounded bg-red-600 text-white hover:bg-red-700 cursor-pointer outline-none py-1 px-2 my-2">Registrarse</a>
            <?php endif; ?>
        </nav>
    </header>
