<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BiblioDevs</title>
</head>
<body>
    <header>
        <figure>
            <img src=<?="{$HOST}assets/images/logo.png"?> alt="logo">
        </figure>
        <nav>
            <a href="">Administrador</a>
            <?php if (isset($_SESSION) 
                && !empty($_SESSION["user_id"])): ?>
                <a href="/user">Cuenta</a>
                <a href="/user/logout">Cerrar sesión</a>
            <?php else: ?>
                <a href="/user/login">Iniciar Sesion</a>
                <a href="/user/signup">Registrarse</a>
            <?php endif; ?>
        </nav>
    </header>
