<div class="w-full flex flex-col items-center">
    <h3 class="text-lg text-center font-bold">Informacion del usuario</h3>
    <div class="grid grid-cols-2 gap-2 max-w-xs">
        <div>
            <p class="font-bold">Nombre:</p>
            <p><?= ($db_user->getNombre()) ?></p>
        </div>
        <div>
            <p class="font-bold">Email:</p>
            <p><?= ($db_user->getEmail()) ?></p>
        </div>
        <div>
            <p class="font-bold">Ocupación:</p>
            <p><?= ($db_user->getOcupacion()) ?></p>
        </div>
        <div>
            
            <p class="font-bold">Año de nacimiento:</p>
            <p><?= ($db_user->getBirthday()) ?></p>
        </div>
        <div>
            <p class="font-bold">País:</p>
            <p><?=(isset($pais)) ? $pais : "N/A"?></p>
        </div>
    </div>
    <div class="flex flex-col justify-between items-center">
        <a href="/user/updateUser" class="text-center w-full border rounded py-1 px-2 my-2 bg-red-600 text-white hover:bg-red-700">Editar</a>
        <a href="/user/changePassword" class="text-center w-full border rounded py-1 px-2 my-2 bg-red-600 text-white hover:bg-red-700">Cambiar contraseña</a>
    </div>
</div>
