<form action="/user/updateUser" method="post">
    <label for="nombre">Nombre:</label>
    <span id="nombre"><?= htmlspecialchars($db_user->getNombre()) ?></span><br>
    <label for="email">Email:</label>
    <span id="email"><?= htmlspecialchars($db_user->getEmail()) ?></span><br>
    <label for="ocupacion">Ocupación:</label>
    <span id="ocupacion"><?= htmlspecialchars($db_user->getOcupacion()) ?></span><br>
    <label for="birthday">Año de nacimiento:</label>
    <span id="birthday"><?= htmlspecialchars($db_user->getBirthday()) ?></span><br>
    <label for="pais">País:</label>
    <span id="pais">
        <?php
            $selectedCountry = "";
            if ($db_user->getIdPais() === 1) {
                $selectedCountry = "El Salvador";
            } elseif ($db_user->getIdPais() === 2) {
                $selectedCountry = "México";
            }
            echo htmlspecialchars($selectedCountry);
        ?>
    </span><br>
    <a href="/user/UpdateUser" id="editarEnlace">Editar</a>
    <a href="/user/UpdatePassword" id="editarEnlace">Editar Contraseña</a>
</form>
