<div class="w-full flex flex-col items-center">
    <h3 class="text-lg text-center font-bold">Inicia sesión</h3>
    <?php if(!empty($errors)):?>
        <?php foreach($errors as $error): ?>
            <p><?=$error?></p><br>
        <?php endforeach;?>
    <?php endif;?>
    <form method="post" class="w-full max-w-xs flex flex-col">
        <div class="my-2">
            <label for="email" class="block">Email: </label>
            <input class="border bg-neutral-50 appearance-none rounded w-full py-1 px-2 focus:bg-white transition duration-300 outline-none focus:border-gray-500" type="email" name="email" id="email">
        </div>
        <div class="my-2">
            <label for="password" class="block">Contraseña: </label>
            <input class="border bg-neutral-50 appearance-none rounded w-full py-1 px-2 focus:bg-white transition duration-300 outline-none focus:border-gray-500" type="password" name="password" id="password">
        </div>
        <input type="submit" value="Iniciar Sesión" class="self-end border rounded bg-red-600 text-white hover:bg-red-700 cursor-pointer outline-none py-1 px-2 my-2">
    </form>
</div>