<h1>Cambiar Contraseña</h1>
<form action="/user/updatePassword" method="post">
    <label for="current_password">Contraseña Actual:</label>
    <input type="password" id="current_password" name="current_password" required>
    <br><br>

    <label for="new_password">Nueva Contraseña:</label>
    <input type="password" id="new_password" name="new_password" required>
    <br><br>

    <label for="confirm_password">Confirmar Nueva Contraseña:</label>
    <input type="password" id="confirm_password" name="confirm_password" required>
    <br><br>

    <input type="submit" value="Cambiar Contraseña">
</form>
