<div class="w-full flex flex-col items-center">
    <h3 class="text-lg text-center font-bold">Cambiar Contraseña</h3>
    <?php require_once Utils::getErrorsView(); ?>
    <form method="post" class="w-full max-w-xs flex flex-col">
        <div class="my-2">
            <label for="current_password">Contraseña Actual:</label>
            <input type="password" id="current_password" name="current_password" required class="border bg-neutral-50 appearance-none rounded w-full py-1 px-2 focus:bg-white transition duration-300 outline-none focus:border-gray-500">
        </div>
        <div class="my-2">
            <label for="new_password">Nueva Contraseña:</label>
            <input type="password" id="new_password" name="new_password" required required class="border bg-neutral-50 appearance-none rounded w-full py-1 px-2 focus:bg-white transition duration-300 outline-none focus:border-gray-500">
        </div>
        <div class="my-2">
            <label for="confirm_password">Confirmar Nueva Contraseña:</label>
            <input type="password" id="confirm_password" name="confirm_password" required class="border bg-neutral-50 appearance-none rounded w-full py-1 px-2 focus:bg-white transition duration-300 outline-none focus:border-gray-500">
        </div>
        <input type="submit" value="Cambiar Contraseña" class="self-end border rounded bg-red outline-none py-1 px-2 my-2 bg-red-600 text-white hover:bg-red-700 cursor-pointer">
    </form>
</div>